
version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: PMV
    volumes:
      - .:/PMV
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin1
      command: -p 5000
      ports: "5000:5433"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
      dbdata: