# Generated by Django 4.1.4 on 2023-02-07 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('api_name', models.CharField(blank=True, max_length=300, null=True)),
                ('phonenumber', models.CharField(max_length=300)),
                ('phonenumber2', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('website', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='uploads/clients/')),
                ('buyingdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('assigned_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=300)),
                ('heading2', models.CharField(blank=True, max_length=300, null=True)),
                ('message', models.TextField()),
                ('receivers', models.ManyToManyField(related_name='receiver', to='home.client')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.CharField(blank=True, max_length=300, null=True)),
                ('notes', models.TextField()),
                ('note_by', models.ManyToManyField(related_name='clients', to='home.client')),
            ],
        ),
    ]
