# Generated by Django 4.1.4 on 2023-01-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comany_name', models.CharField(max_length=300)),
                ('phonenumber', models.CharField(max_length=300)),
                ('phonenumber2', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('website', models.EmailField(max_length=300)),
                ('logo', models.ImageField(storage='static', upload_to='')),
                ('buyingdate', models.DateField()),
            ],
        ),
    ]
