# Generated by Django 4.1.4 on 2023-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.CharField(max_length=300),
        ),
    ]
