# Generated by Django 4.1.4 on 2023-03-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_ticket_assigned_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='api_name',
            field=models.CharField(default='apiclient', max_length=300),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/clients/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
