# Generated by Django 4.1.4 on 2023-03-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_client_address_alter_client_api_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, default='https://zergaw.com/wp-content/uploads/2021/10/Logo-1-70x70.png', null=True, upload_to='uploads/clients/'),
        ),
    ]
