# Generated by Django 4.1.4 on 2023-01-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_client_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
