# Generated by Django 4.1.4 on 2023-01-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_client_api_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='comany_name',
            new_name='company_name',
        ),
    ]
