# Generated by Django 4.1.4 on 2023-06-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vmid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
