name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: intializing build
    runs-on: debian

    steps:
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        source venv/bin/activate
        cd PMV
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
