name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
   group: master
   cancel-in-progress: true

jobs:
  build:
    name: intializing build
    runs-on: debian

    steps:
    - uses: actions/checkout@v2
    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
        chmod 600 ~/.ssh/github
        cat >>~/.ssh/config <<END
        Host target
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/github
          LogLevel ERROR
          StrictHostKeyChecking no
        END
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        source venv/bin/activate
        cd PMV
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
